### ISSUE TITLE
Better filter pitch tracking

### ISSUE THREAD

**Issue by jonikorpi** [vuoro/pelimanni#10]
Currently pitch tracking lerps filter cutoff towards the pitch. This is just weird. Better just have it multiply the cutoff frequency.

- [x] Make the change
- [x] Update presets
  - [x] hammeredDulcimer should have massive tracking, which may require adjusting cutoffs to compensate 
  - [x] brass should have some negative lowpass tracking
